//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay.PlasmaTechUnitedSolutions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://booking.us.org/", ConfigurationName="PlasmaTechUnitedSolutions.UnitedSolutions")]
    public interface UnitedSolutions {
        
        // CODEGEN: Generating message contract since element name strFlightId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/ReservationRequest", ReplyAction="http://booking.us.org/UnitedSolutions/ReservationResponse")]
        MyPay.PlasmaTechUnitedSolutions.ReservationResponse Reservation(MyPay.PlasmaTechUnitedSolutions.ReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/ReservationRequest", ReplyAction="http://booking.us.org/UnitedSolutions/ReservationResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.ReservationResponse> ReservationAsync(MyPay.PlasmaTechUnitedSolutions.ReservationRequest request);
        
        // CODEGEN: Generating message contract since element name strFlightId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/IssueTicketRequest", ReplyAction="http://booking.us.org/UnitedSolutions/IssueTicketResponse")]
        MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse IssueTicket(MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/IssueTicketRequest", ReplyAction="http://booking.us.org/UnitedSolutions/IssueTicketResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse> IssueTicketAsync(MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest request);
        
        // CODEGEN: Generating message contract since element name strUserId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/FlightAvailabilityRequest", ReplyAction="http://booking.us.org/UnitedSolutions/FlightAvailabilityResponse")]
        MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse FlightAvailability(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/FlightAvailabilityRequest", ReplyAction="http://booking.us.org/UnitedSolutions/FlightAvailabilityResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse> FlightAvailabilityAsync(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest request);
        
        // CODEGEN: Generating message contract since element name strUserId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/SectorCodeRequest", ReplyAction="http://booking.us.org/UnitedSolutions/SectorCodeResponse")]
        MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse SectorCode(MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/SectorCodeRequest", ReplyAction="http://booking.us.org/UnitedSolutions/SectorCodeResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse> SectorCodeAsync(MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest request);
        
        // CODEGEN: Generating message contract since element name strPnoNo from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/GetItineraryRequest", ReplyAction="http://booking.us.org/UnitedSolutions/GetItineraryResponse")]
        MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse GetItinerary(MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/GetItineraryRequest", ReplyAction="http://booking.us.org/UnitedSolutions/GetItineraryResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse> GetItineraryAsync(MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest request);
        
        // CODEGEN: Generating message contract since element name strUserId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/SalesReportRequest", ReplyAction="http://booking.us.org/UnitedSolutions/SalesReportResponse")]
        MyPay.PlasmaTechUnitedSolutions.SalesReportResponse SalesReport(MyPay.PlasmaTechUnitedSolutions.SalesReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/SalesReportRequest", ReplyAction="http://booking.us.org/UnitedSolutions/SalesReportResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SalesReportResponse> SalesReportAsync(MyPay.PlasmaTechUnitedSolutions.SalesReportRequest request);
        
        // CODEGEN: Generating message contract since element name strFlightId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/IssueTicketB2BRequest", ReplyAction="http://booking.us.org/UnitedSolutions/IssueTicketB2BResponse")]
        MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse IssueTicketB2B(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/IssueTicketB2BRequest", ReplyAction="http://booking.us.org/UnitedSolutions/IssueTicketB2BResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse> IssueTicketB2BAsync(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest request);
        
        // CODEGEN: Generating message contract since element name strUserId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/GetFlightDetailRequest", ReplyAction="http://booking.us.org/UnitedSolutions/GetFlightDetailResponse")]
        MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse GetFlightDetail(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/GetFlightDetailRequest", ReplyAction="http://booking.us.org/UnitedSolutions/GetFlightDetailResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse> GetFlightDetailAsync(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest request);
        
        // CODEGEN: Generating message contract since element name strUserId from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/CheckBalanceRequest", ReplyAction="http://booking.us.org/UnitedSolutions/CheckBalanceResponse")]
        MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse CheckBalance(MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://booking.us.org/UnitedSolutions/CheckBalanceRequest", ReplyAction="http://booking.us.org/UnitedSolutions/CheckBalanceResponse")]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse> CheckBalanceAsync(MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reservation", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.ReservationRequestBody Body;
        
        public ReservationRequest() {
        }
        
        public ReservationRequest(MyPay.PlasmaTechUnitedSolutions.ReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFlightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strReturnFlightId;
        
        public ReservationRequestBody() {
        }
        
        public ReservationRequestBody(string strFlightId, string strReturnFlightId) {
            this.strFlightId = strFlightId;
            this.strReturnFlightId = strReturnFlightId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservationResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.ReservationResponseBody Body;
        
        public ReservationResponse() {
        }
        
        public ReservationResponse(MyPay.PlasmaTechUnitedSolutions.ReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ReservationResponseBody() {
        }
        
        public ReservationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueTicket", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.IssueTicketRequestBody Body;
        
        public IssueTicketRequest() {
        }
        
        public IssueTicketRequest(MyPay.PlasmaTechUnitedSolutions.IssueTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IssueTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFlightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strReturnFlightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strContactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strContactEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strContactMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strPassengerDetail;
        
        public IssueTicketRequestBody() {
        }
        
        public IssueTicketRequestBody(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            this.strFlightId = strFlightId;
            this.strReturnFlightId = strReturnFlightId;
            this.strContactName = strContactName;
            this.strContactEmail = strContactEmail;
            this.strContactMobile = strContactMobile;
            this.strPassengerDetail = strPassengerDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueTicketResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.IssueTicketResponseBody Body;
        
        public IssueTicketResponse() {
        }
        
        public IssueTicketResponse(MyPay.PlasmaTechUnitedSolutions.IssueTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IssueTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public IssueTicketResponseBody() {
        }
        
        public IssueTicketResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightAvailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FlightAvailability", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequestBody Body;
        
        public FlightAvailabilityRequest() {
        }
        
        public FlightAvailabilityRequest(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class FlightAvailabilityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAgencyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strSectorFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSectorTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strFlightDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strReturnDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strTripType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strNationality;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string intAdult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string intChild;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string strClientIP;
        
        public FlightAvailabilityRequestBody() {
        }
        
        public FlightAvailabilityRequestBody(string strUserId, string strPassword, string strAgencyId, string strSectorFrom, string strSectorTo, string strFlightDate, string strReturnDate, string strTripType, string strNationality, string intAdult, string intChild, string strClientIP) {
            this.strUserId = strUserId;
            this.strPassword = strPassword;
            this.strAgencyId = strAgencyId;
            this.strSectorFrom = strSectorFrom;
            this.strSectorTo = strSectorTo;
            this.strFlightDate = strFlightDate;
            this.strReturnDate = strReturnDate;
            this.strTripType = strTripType;
            this.strNationality = strNationality;
            this.intAdult = intAdult;
            this.intChild = intChild;
            this.strClientIP = strClientIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FlightAvailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FlightAvailabilityResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponseBody Body;
        
        public FlightAvailabilityResponse() {
        }
        
        public FlightAvailabilityResponse(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class FlightAvailabilityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public FlightAvailabilityResponseBody() {
        }
        
        public FlightAvailabilityResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SectorCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SectorCode", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.SectorCodeRequestBody Body;
        
        public SectorCodeRequest() {
        }
        
        public SectorCodeRequest(MyPay.PlasmaTechUnitedSolutions.SectorCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SectorCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserId;
        
        public SectorCodeRequestBody() {
        }
        
        public SectorCodeRequestBody(string strUserId) {
            this.strUserId = strUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SectorCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SectorCodeResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.SectorCodeResponseBody Body;
        
        public SectorCodeResponse() {
        }
        
        public SectorCodeResponse(MyPay.PlasmaTechUnitedSolutions.SectorCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SectorCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SectorCodeResponseBody() {
        }
        
        public SectorCodeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItineraryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItinerary", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.GetItineraryRequestBody Body;
        
        public GetItineraryRequest() {
        }
        
        public GetItineraryRequest(MyPay.PlasmaTechUnitedSolutions.GetItineraryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetItineraryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strPnoNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strTicketNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAgencyId;
        
        public GetItineraryRequestBody() {
        }
        
        public GetItineraryRequestBody(string strPnoNo, string strTicketNo, string strAgencyId) {
            this.strPnoNo = strPnoNo;
            this.strTicketNo = strTicketNo;
            this.strAgencyId = strAgencyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItineraryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItineraryResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.GetItineraryResponseBody Body;
        
        public GetItineraryResponse() {
        }
        
        public GetItineraryResponse(MyPay.PlasmaTechUnitedSolutions.GetItineraryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetItineraryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetItineraryResponseBody() {
        }
        
        public GetItineraryResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesReport", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.SalesReportRequestBody Body;
        
        public SalesReportRequest() {
        }
        
        public SalesReportRequest(MyPay.PlasmaTechUnitedSolutions.SalesReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SalesReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strAgencyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strToDate;
        
        public SalesReportRequestBody() {
        }
        
        public SalesReportRequestBody(string strUserId, string strPassword, string strAgencyId, string strFromDate, string strToDate) {
            this.strUserId = strUserId;
            this.strPassword = strPassword;
            this.strAgencyId = strAgencyId;
            this.strFromDate = strFromDate;
            this.strToDate = strToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesReportResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.SalesReportResponseBody Body;
        
        public SalesReportResponse() {
        }
        
        public SalesReportResponse(MyPay.PlasmaTechUnitedSolutions.SalesReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SalesReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SalesReportResponseBody() {
        }
        
        public SalesReportResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueTicketB2BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueTicketB2B", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequestBody Body;
        
        public IssueTicketB2BRequest() {
        }
        
        public IssueTicketB2BRequest(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IssueTicketB2BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFlightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strReturnFlightId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strContactName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strContactEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strContactMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strPassengerDetail;
        
        public IssueTicketB2BRequestBody() {
        }
        
        public IssueTicketB2BRequestBody(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            this.strFlightId = strFlightId;
            this.strReturnFlightId = strReturnFlightId;
            this.strContactName = strContactName;
            this.strContactEmail = strContactEmail;
            this.strContactMobile = strContactMobile;
            this.strPassengerDetail = strPassengerDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IssueTicketB2BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IssueTicketB2BResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponseBody Body;
        
        public IssueTicketB2BResponse() {
        }
        
        public IssueTicketB2BResponse(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IssueTicketB2BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public IssueTicketB2BResponseBody() {
        }
        
        public IssueTicketB2BResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlightDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightDetail", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequestBody Body;
        
        public GetFlightDetailRequest() {
        }
        
        public GetFlightDetailRequest(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetFlightDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFlightId;
        
        public GetFlightDetailRequestBody() {
        }
        
        public GetFlightDetailRequestBody(string strUserId, string strFlightId) {
            this.strUserId = strUserId;
            this.strFlightId = strFlightId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlightDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightDetailResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponseBody Body;
        
        public GetFlightDetailResponse() {
        }
        
        public GetFlightDetailResponse(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetFlightDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetFlightDetailResponseBody() {
        }
        
        public GetFlightDetailResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBalance", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequestBody Body;
        
        public CheckBalanceRequest() {
        }
        
        public CheckBalanceRequest(MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strAirlineId;
        
        public CheckBalanceRequestBody() {
        }
        
        public CheckBalanceRequestBody(string strUserId, string strAirlineId) {
            this.strUserId = strUserId;
            this.strAirlineId = strAirlineId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBalanceResponse", Namespace="http://booking.us.org/", Order=0)]
        public MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponseBody Body;
        
        public CheckBalanceResponse() {
        }
        
        public CheckBalanceResponse(MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CheckBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CheckBalanceResponseBody() {
        }
        
        public CheckBalanceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UnitedSolutionsChannel : MyPay.PlasmaTechUnitedSolutions.UnitedSolutions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnitedSolutionsClient : System.ServiceModel.ClientBase<MyPay.PlasmaTechUnitedSolutions.UnitedSolutions>, MyPay.PlasmaTechUnitedSolutions.UnitedSolutions {
        
        public UnitedSolutionsClient() {
        }
        
        public UnitedSolutionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnitedSolutionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitedSolutionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitedSolutionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.ReservationResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.Reservation(MyPay.PlasmaTechUnitedSolutions.ReservationRequest request) {
            return base.Channel.Reservation(request);
        }
        
        public string Reservation(string strFlightId, string strReturnFlightId) {
            MyPay.PlasmaTechUnitedSolutions.ReservationRequest inValue = new MyPay.PlasmaTechUnitedSolutions.ReservationRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.ReservationRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            MyPay.PlasmaTechUnitedSolutions.ReservationResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).Reservation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.ReservationResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.ReservationAsync(MyPay.PlasmaTechUnitedSolutions.ReservationRequest request) {
            return base.Channel.ReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.ReservationResponse> ReservationAsync(string strFlightId, string strReturnFlightId) {
            MyPay.PlasmaTechUnitedSolutions.ReservationRequest inValue = new MyPay.PlasmaTechUnitedSolutions.ReservationRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.ReservationRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).ReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.IssueTicket(MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest request) {
            return base.Channel.IssueTicket(request);
        }
        
        public string IssueTicket(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest inValue = new MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.IssueTicketRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            inValue.Body.strContactName = strContactName;
            inValue.Body.strContactEmail = strContactEmail;
            inValue.Body.strContactMobile = strContactMobile;
            inValue.Body.strPassengerDetail = strPassengerDetail;
            MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).IssueTicket(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.IssueTicketAsync(MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest request) {
            return base.Channel.IssueTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketResponse> IssueTicketAsync(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest inValue = new MyPay.PlasmaTechUnitedSolutions.IssueTicketRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.IssueTicketRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            inValue.Body.strContactName = strContactName;
            inValue.Body.strContactEmail = strContactEmail;
            inValue.Body.strContactMobile = strContactMobile;
            inValue.Body.strPassengerDetail = strPassengerDetail;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).IssueTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.FlightAvailability(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest request) {
            return base.Channel.FlightAvailability(request);
        }
        
        public string FlightAvailability(string strUserId, string strPassword, string strAgencyId, string strSectorFrom, string strSectorTo, string strFlightDate, string strReturnDate, string strTripType, string strNationality, string intAdult, string intChild, string strClientIP) {
            MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest inValue = new MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strAgencyId = strAgencyId;
            inValue.Body.strSectorFrom = strSectorFrom;
            inValue.Body.strSectorTo = strSectorTo;
            inValue.Body.strFlightDate = strFlightDate;
            inValue.Body.strReturnDate = strReturnDate;
            inValue.Body.strTripType = strTripType;
            inValue.Body.strNationality = strNationality;
            inValue.Body.intAdult = intAdult;
            inValue.Body.intChild = intChild;
            inValue.Body.strClientIP = strClientIP;
            MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).FlightAvailability(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.FlightAvailabilityAsync(MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest request) {
            return base.Channel.FlightAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityResponse> FlightAvailabilityAsync(string strUserId, string strPassword, string strAgencyId, string strSectorFrom, string strSectorTo, string strFlightDate, string strReturnDate, string strTripType, string strNationality, string intAdult, string intChild, string strClientIP) {
            MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest inValue = new MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.FlightAvailabilityRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strAgencyId = strAgencyId;
            inValue.Body.strSectorFrom = strSectorFrom;
            inValue.Body.strSectorTo = strSectorTo;
            inValue.Body.strFlightDate = strFlightDate;
            inValue.Body.strReturnDate = strReturnDate;
            inValue.Body.strTripType = strTripType;
            inValue.Body.strNationality = strNationality;
            inValue.Body.intAdult = intAdult;
            inValue.Body.intChild = intChild;
            inValue.Body.strClientIP = strClientIP;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).FlightAvailabilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.SectorCode(MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest request) {
            return base.Channel.SectorCode(request);
        }
        
        public string SectorCode(string strUserId) {
            MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest inValue = new MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.SectorCodeRequestBody();
            inValue.Body.strUserId = strUserId;
            MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).SectorCode(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.SectorCodeAsync(MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest request) {
            return base.Channel.SectorCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SectorCodeResponse> SectorCodeAsync(string strUserId) {
            MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest inValue = new MyPay.PlasmaTechUnitedSolutions.SectorCodeRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.SectorCodeRequestBody();
            inValue.Body.strUserId = strUserId;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).SectorCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.GetItinerary(MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest request) {
            return base.Channel.GetItinerary(request);
        }
        
        public string GetItinerary(string strPnoNo, string strTicketNo, string strAgencyId) {
            MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest inValue = new MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.GetItineraryRequestBody();
            inValue.Body.strPnoNo = strPnoNo;
            inValue.Body.strTicketNo = strTicketNo;
            inValue.Body.strAgencyId = strAgencyId;
            MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).GetItinerary(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.GetItineraryAsync(MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest request) {
            return base.Channel.GetItineraryAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetItineraryResponse> GetItineraryAsync(string strPnoNo, string strTicketNo, string strAgencyId) {
            MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest inValue = new MyPay.PlasmaTechUnitedSolutions.GetItineraryRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.GetItineraryRequestBody();
            inValue.Body.strPnoNo = strPnoNo;
            inValue.Body.strTicketNo = strTicketNo;
            inValue.Body.strAgencyId = strAgencyId;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).GetItineraryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.SalesReportResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.SalesReport(MyPay.PlasmaTechUnitedSolutions.SalesReportRequest request) {
            return base.Channel.SalesReport(request);
        }
        
        public string SalesReport(string strUserId, string strPassword, string strAgencyId, string strFromDate, string strToDate) {
            MyPay.PlasmaTechUnitedSolutions.SalesReportRequest inValue = new MyPay.PlasmaTechUnitedSolutions.SalesReportRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.SalesReportRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strAgencyId = strAgencyId;
            inValue.Body.strFromDate = strFromDate;
            inValue.Body.strToDate = strToDate;
            MyPay.PlasmaTechUnitedSolutions.SalesReportResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).SalesReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SalesReportResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.SalesReportAsync(MyPay.PlasmaTechUnitedSolutions.SalesReportRequest request) {
            return base.Channel.SalesReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.SalesReportResponse> SalesReportAsync(string strUserId, string strPassword, string strAgencyId, string strFromDate, string strToDate) {
            MyPay.PlasmaTechUnitedSolutions.SalesReportRequest inValue = new MyPay.PlasmaTechUnitedSolutions.SalesReportRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.SalesReportRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strAgencyId = strAgencyId;
            inValue.Body.strFromDate = strFromDate;
            inValue.Body.strToDate = strToDate;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).SalesReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.IssueTicketB2B(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest request) {
            return base.Channel.IssueTicketB2B(request);
        }
        
        public string IssueTicketB2B(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest inValue = new MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            inValue.Body.strContactName = strContactName;
            inValue.Body.strContactEmail = strContactEmail;
            inValue.Body.strContactMobile = strContactMobile;
            inValue.Body.strPassengerDetail = strPassengerDetail;
            MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).IssueTicketB2B(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.IssueTicketB2BAsync(MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest request) {
            return base.Channel.IssueTicketB2BAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BResponse> IssueTicketB2BAsync(string strFlightId, string strReturnFlightId, string strContactName, string strContactEmail, string strContactMobile, string strPassengerDetail) {
            MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest inValue = new MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.IssueTicketB2BRequestBody();
            inValue.Body.strFlightId = strFlightId;
            inValue.Body.strReturnFlightId = strReturnFlightId;
            inValue.Body.strContactName = strContactName;
            inValue.Body.strContactEmail = strContactEmail;
            inValue.Body.strContactMobile = strContactMobile;
            inValue.Body.strPassengerDetail = strPassengerDetail;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).IssueTicketB2BAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.GetFlightDetail(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest request) {
            return base.Channel.GetFlightDetail(request);
        }
        
        public string GetFlightDetail(string strUserId, string strFlightId) {
            MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest inValue = new MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strFlightId = strFlightId;
            MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).GetFlightDetail(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.GetFlightDetailAsync(MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest request) {
            return base.Channel.GetFlightDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.GetFlightDetailResponse> GetFlightDetailAsync(string strUserId, string strFlightId) {
            MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest inValue = new MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.GetFlightDetailRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strFlightId = strFlightId;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).GetFlightDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.CheckBalance(MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest request) {
            return base.Channel.CheckBalance(request);
        }
        
        public string CheckBalance(string strUserId, string strAirlineId) {
            MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest inValue = new MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strAirlineId = strAirlineId;
            MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse retVal = ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).CheckBalance(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse> MyPay.PlasmaTechUnitedSolutions.UnitedSolutions.CheckBalanceAsync(MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest request) {
            return base.Channel.CheckBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyPay.PlasmaTechUnitedSolutions.CheckBalanceResponse> CheckBalanceAsync(string strUserId, string strAirlineId) {
            MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest inValue = new MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequest();
            inValue.Body = new MyPay.PlasmaTechUnitedSolutions.CheckBalanceRequestBody();
            inValue.Body.strUserId = strUserId;
            inValue.Body.strAirlineId = strAirlineId;
            return ((MyPay.PlasmaTechUnitedSolutions.UnitedSolutions)(this)).CheckBalanceAsync(inValue);
        }
    }
}
