//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int CountryId { get; set; }
        public string TransactionPassword { get; set; }
        public string Image { get; set; }
        public long MemberId { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string IpAddress { get; set; }
        public long StoreId { get; set; }
        public long EquipmentId { get; set; }
        public string StoreName { get; set; }
        public string DeviceToken { get; set; }
        public string SessionId { get; set; }
        public string VerificationCode { get; set; }
        public int StateId { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public int DistrictId { get; set; }
        public int MunicipalityId { get; set; }
        public string Municipality { get; set; }
        public string ServiceStatus { get; set; }
        public System.DateTime LastServiceConnected { get; set; }
        public bool IsPasswordExpired { get; set; }
        public System.DateTime PasswordExpireDate { get; set; }
    }
}
