//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline_Commissions
    {
        public int Id { get; set; }
        public string ToDestination { get; set; }
        public string FromDestination { get; set; }
        public System.DateTime Date { get; set; }
        public string TicketNo { get; set; }
        public string PNRNo { get; set; }
        public decimal CommissionPercReceived { get; set; }
        public decimal CommissionAmtReceived { get; set; }
        public decimal TicketPrice { get; set; }
        public decimal CashbackGiven { get; set; }
    }
}
