//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiSetting
    {
        public long Id { get; set; }
        public int CheckVersion { get; set; }
        public int CheckDevicecode { get; set; }
        public int CheckAndroidVersion { get; set; }
        public int CheckTimestamp { get; set; }
        public int CheckHash { get; set; }
        public int CheckPlatform { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime ScheduleStartTime { get; set; }
        public System.DateTime ScheduleEndTime { get; set; }
        public string SchedulerMessage { get; set; }
        public bool ScheduleStatus { get; set; }
        public string AndroidVersion { get; set; }
        public string IOSVersion { get; set; }
        public int BankTransferType { get; set; }
        public System.DateTime MPCoinsDateSettings { get; set; }
        public System.DateTime ActivityMonitorLastUpdate { get; set; }
        public int LinkBankTransferType { get; set; }
    }
}
