//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{

    using System;
    using System.Collections.Generic;

    public partial class CableCarCommon
    {

        public string  TransactionId{ get; set; }

        public long CableId { get; set; }
        public string ReferenceNumber { get; set; }
        public string ResponseCode { get; set;}
        public int Id { get; set; }
    }

}