//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CableCar_TicketInVoice
    {
        public int TicketId { get; set; }
        public string TripType { get; set; }
        public string PassengerType { get; set; }
        public string QRCode { get; set; }
        public string BarCode { get; set; }
        public string ValidUntil { get; set; }
        public string TicketNumber { get; set; }
        public string BasePrice { get; set; }
        public string VatTax { get; set; }
        public string TotalAmount { get; set; }
        public string ReferenceId { get; set; }
        public string TicketMessage { get; set; }
        public string VatBillMessage { get; set; }
        public string Username { get; set; }
    }
}
