//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponsScratched
    {
        public long Id { get; set; }
        public long CouponId { get; set; }
        public int CouponType { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long MemberId { get; set; }
        public string MemberName { get; set; }
        public string ContactNumber { get; set; }
        public string CouponCode { get; set; }
        public int ServiceId { get; set; }
        public decimal CouponAmount { get; set; }
        public decimal CouponPercentage { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int IsUsed { get; set; }
        public int IsExpired { get; set; }
        public int IsScratched { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public long UpdatedBy { get; set; }
        public string UniqueTransactionId { get; set; }
        public string ParentTransactionId { get; set; }
        public string Remarks { get; set; }
        public int Type { get; set; }
        public string UsedByTransactionId { get; set; }
        public int CouponApplyType { get; set; }
        public decimal MinimumAmount { get; set; }
        public decimal MaximumAmount { get; set; }
    }
}
