//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPackDetail
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public int PriorityNo { get; set; }
        public string ProductName { get; set; }
        public decimal Amount { get; set; }
        public string ShortDetail { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public string ProductType { get; set; }
        public string Validity { get; set; }
        public bool IsPurchased { get; set; }
        public string ContactNumber { get; set; }
        public long PackageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string ReceiptPDF { get; set; }
    }
}
