//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsAndOffer
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public int CouponType { get; set; }
        public int KycStatus { get; set; }
        public int GenderStatus { get; set; }
        public decimal Amount { get; set; }
        public decimal CouponPercentage { get; set; }
        public int CouponsCount { get; set; }
        public int CouponsUsedCount { get; set; }
        public int ServiceId { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public long UpdatedBy { get; set; }
        public long TransactionCount { get; set; }
        public decimal TransactionVolume { get; set; }
        public int IsOneTime { get; set; }
        public int IsOneTimePerDay { get; set; }
        public int ApplyType { get; set; }
        public decimal MinimumAmount { get; set; }
        public decimal MaximumAmount { get; set; }
        public string PromoCode { get; set; }
        public string Image { get; set; }
        public string CouponValue { get; set; }
        public string CouponQuantity { get; set; }
        public Nullable<long> campaignId { get; set; }
    }
}
