//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftMPCoinsHistory
    {
        public long Id { get; set; }
        public string ContactNumber { get; set; }
        public decimal Prize { get; set; }
        public string TransactionId { get; set; }
        public string Remarks { get; set; }
        public int Sign { get; set; }
        public long MemberId { get; set; }
        public string MemberName { get; set; }
        public int Status { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
    }
}
