//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceDetail
    {
        public long Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string NextDueDate { get; set; }
        public string ProductName { get; set; }
        public decimal FineAmount { get; set; }
        public string InvoiceNumber { get; set; }
        public string TransactionId { get; set; }
        public string PolicyType { get; set; }
        public string PolicyCategory { get; set; }
        public decimal Amount { get; set; }
        public string Reference { get; set; }
        public string PolicyNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ServiceName { get; set; }
        public string InsuranceSlug { get; set; }
        public string TaxInvoiceNo { get; set; }
        public string ReceiptNo { get; set; }
        public string DocumentNo { get; set; }
        public long InsuranceId { get; set; }
        public int InsuranceType { get; set; }
        public int VendorType { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public long Updatedby { get; set; }
        public string DebitNoteNo { get; set; }
        public long SessionId { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
        public long RequestId { get; set; }
        public string ProformaNo { get; set; }
        public decimal TpPremium { get; set; }
        public decimal SumInsured { get; set; }
        public string Insured { get; set; }
        public string ClassName { get; set; }
        public string DateOfBirth { get; set; }
        public string Paymode { get; set; }
        public decimal TotalFine { get; set; }
        public decimal RebateAmount { get; set; }
        public string PaymentDate { get; set; }
        public string DueDate { get; set; }
        public string PolicyStatus { get; set; }
        public int Term { get; set; }
        public string MaturityDate { get; set; }
        public string UniqueIdGUID { get; set; }
        public int ErrorCode { get; set; }
        public string Error { get; set; }
        public decimal CreditsConsumed { get; set; }
        public decimal CreditsAvailable { get; set; }
        public string PlanCode { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public string ExpiryDate { get; set; }
        public string CoverageType { get; set; }
        public string ids { get; set; }
        public string TransactionUniqueId { get; set; }
        public long MemberId { get; set; }
        public string IpAddress { get; set; }
        public decimal WalletBalance { get; set; }
    }
}
