//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenusAppUser
    {
        public long Id { get; set; }
        public string MenuName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Url { get; set; }
        public int ParentId { get; set; }
        public string Icon { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public bool IsInnerURL { get; set; }
    }
}
