//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantOrder
    {
        public long Id { get; set; }
        public string MerchantId { get; set; }
        public string MerchantName { get; set; }
        public string OrganizationName { get; set; }
        public string MerchantContactNo { get; set; }
        public string OrderId { get; set; }
        public string TransactionId { get; set; }
        public long MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberContactNumber { get; set; }
        public int Status { get; set; }
        public string Remarks { get; set; }
        public string Particulars { get; set; }
        public decimal Amount { get; set; }
        public string TrackerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public int Type { get; set; }
        public decimal ServiceCharges { get; set; }
        public string IpAddress { get; set; }
        public string Platform { get; set; }
        public string DeviceCode { get; set; }
        public string OrderToken { get; set; }
        public long UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public string OrderOTP { get; set; }
        public int Sign { get; set; }
        public decimal CurrentBalance { get; set; }
        public int OTPAttemptCount { get; set; }
        public string ParentTransactionId { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal CashbackAmount { get; set; }
        public decimal MerchantContributionPercentage { get; set; }
        public string ReturnUrl { get; set; }
    }
}
