//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPayment
    {
        public int Id { get; set; }
        public string JsonData { get; set; }
        public string ProviderName { get; set; }
        public string ProviderTypeId { get; set; }
        public string memberID { get; set; }
    }
}
