//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class NepalPayQR_Refund
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string OrginalTxnId { get; set; }
        public string RefundedTxnId { get; set; }
        public string InstructionId { get; set; }
        public decimal Amount { get; set; }
        public string RefundType { get; set; }
        public string Status { get; set; }
        public string IssuerId { get; set; }
        public Nullable<decimal> TransactionFee { get; set; }
        public string RefundReasonMessage { get; set; }
        public string PayerPanId { get; set; }
        public string PayerMobileNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string MyPayOrginalTxnId { get; set; }
        public string MyPayRefundedTxnId { get; set; }
        public string nQrTxnId { get; set; }
    }
}
