//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCampaign
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationDescription { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime SentDate { get; set; }
        public int SentStatus { get; set; }
        public int GenderStatus { get; set; }
        public int KycStatus { get; set; }
        public int IsOldUserStatus { get; set; }
        public long TotalNotificationSent { get; set; }
        public int CurrentSkipIndex { get; set; }
        public int IsCompleted { get; set; }
        public int DeviceTypeStatus { get; set; }
        public string NotificationImage { get; set; }
        public int NotificationRedirectType { get; set; }
        public System.DateTime ScheduleDateTime { get; set; }
        public string URL { get; set; }
        public int Geography { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
    }
}
