//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInactiveRemark
    {
        public long Id { get; set; }
        public int ServiceId { get; set; }
        public string Remarks { get; set; }
        public string Action { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string Sno { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsActive { get; set; }
    }
}
