//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareReferLink
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string RefCode { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsOpened { get; set; }
        public string Platform { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string SharedLinkURL { get; set; }
    }
}
