//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSF
    {
        public long id { get; set; }
        public string submissionNo { get; set; }
        public string EmployerNo { get; set; }
        public string EmployeeNo { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> status { get; set; }
        public string transactionID { get; set; }
    }
}
