//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_passenger_name
    {
        public long PassengerTypeId { get; set; }
        public string PassengerName { get; set; }
        public string PassengerSeat { get; set; }
        public string Gender { get; set; }
        public string PassengerType { get; set; }
        public Nullable<long> Pessangerdetailid { get; set; }
        public string FatherName { get; set; }
    }
}
