//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Passenger_Detail
    {
        public long PassengerDetailId { get; set; }
        public Nullable<int> InputCode { get; set; }
        public string id { get; set; }
        public string ContactNumber { get; set; }
        public string email { get; set; }
        public string PassengerName { get; set; }
        public string PassengerBoardingPoint { get; set; }
    }
}
