//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_api_log
    {
        public long apiLogId { get; set; }
        public Nullable<long> txnId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string functionName { get; set; }
        public string apiRequest { get; set; }
        public string apiResponse { get; set; }
        public string partnerTxnId { get; set; }
        public Nullable<int> partnerId { get; set; }
        public Nullable<System.DateTime> createdUTCDate { get; set; }
        public Nullable<System.DateTime> createdLocalDate { get; set; }
        public string createdBy { get; set; }
        public string createdIp { get; set; }
        public string createdPlatform { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedUTCDate { get; set; }
        public Nullable<System.DateTime> updatedLocalDate { get; set; }
        public string updatedIp { get; set; }
    }
}
