//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusSewa_details
    {
        public long BusDetailId { get; set; }
        public string TripFrom { get; set; }
        public string TripTo { get; set; }
        public string Id { get; set; }
        public string TicketSerialNo { get; set; }
        public Nullable<long> NoOfSeat { get; set; }
        public string BoardingPoint { get; set; }
        public string Seat { get; set; }
        public Nullable<bool> isCancel { get; set; }
        public Nullable<long> PassengerDetailId { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string Operator { get; set; }
        public string BusType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string PaymentStatus { get; set; }
        public string Platform { get; set; }
        public string DeviceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string WalletTransactionId { get; set; }
        public string BusNo { get; set; }
        public string DepartureTime { get; set; }
        public string operatorcontactInfo { get; set; }
    }
}
