//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_error_log_sql
    {
        public long sqlErrorId { get; set; }
        public string sqlErrorDesc { get; set; }
        public string sqlErrorScript { get; set; }
        public string sqlQueryString { get; set; }
        public string sqlErrorCategory { get; set; }
        public string sqlErrorSource { get; set; }
        public Nullable<System.DateTime> sqlErrorUTCDate { get; set; }
        public Nullable<System.DateTime> sqlErrorLocalDate { get; set; }
        public string CreatedPlatform { get; set; }
    }
}
