//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsReply
    {
        public long Id { get; set; }
        public string TicketId { get; set; }
        public string Message { get; set; }
        public string AttachFile { get; set; }
        public int Type { get; set; }
        public long CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsApprovedByAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsNote { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public bool IsMainMessage { get; set; }
    }
}
