//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristBus_Detail
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string CompanyName { get; set; }
        public string Ticketno { get; set; }
        public string from_Location { get; set; }
        public string to_Location { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
        public string staffnum { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Cashback { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public string Seat { get; set; }
        public string TotalSeat { get; set; }
        public string Pickup_Location { get; set; }
        public string BusNo { get; set; }
        public string WalletTransactionId { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string drop_Location { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
