//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting_Orders
    {
        public long Id { get; set; }
        public Nullable<long> memberID { get; set; }
        public string memberName { get; set; }
        public string memberContactNumber { get; set; }
        public Nullable<long> contestID { get; set; }
        public Nullable<int> subcontestID { get; set; }
        public string deviceCode { get; set; }
        public Nullable<long> votingCandidateUniqueId { get; set; }
        public string votingCadidateName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<decimal> PricePerVote { get; set; }
        public Nullable<int> NoOfVotes { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> isPaidVote { get; set; }
        public Nullable<bool> isPackageUsed { get; set; }
        public Nullable<long> votingPackageID { get; set; }
        public Nullable<decimal> serviceCharge { get; set; }
        public string couponCode { get; set; }
        public Nullable<long> createdBy { get; set; }
        public string createdByName { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string platform { get; set; }
        public Nullable<long> orderId { get; set; }
        public string merchantID { get; set; }
        public string TransactionUniqueID { get; set; }
        public string paymentMethodId { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
